INSERT INTO items (isactive, name) VALUES (0, "Gladyce Bosco");
INSERT INTO items (isactive, name) VALUES (1, "Dr. Sherman Sipes MD");
INSERT INTO items (isactive, name) VALUES (1, "Mrs. Ola Gorczany");
INSERT INTO items (isactive, name) VALUES (0, "Mr. Sven Dach Jr.");
INSERT INTO items (isactive, name) VALUES (1, "Mr. Merle Sauer");
INSERT INTO items (isactive, name) VALUES (1, "Monica Huels");
INSERT INTO items (isactive, name) VALUES (0, "Mrs. Oren Fadel DVM");
INSERT INTO items (isactive, name) VALUES (1, "Raoul Doyle");
INSERT INTO items (isactive, name) VALUES (1, "Kolby Fay");
INSERT INTO items (isactive, name) VALUES (0, "Clementine Johnston IV");
INSERT INTO items (isactive, name) VALUES (1, "Marquis Lynch IV");
INSERT INTO items (isactive, name) VALUES (1, "Dale Ward");
INSERT INTO items (isactive, name) VALUES (0, "Luna Schaden");
INSERT INTO items (isactive, name) VALUES (1, "Miss Vivienne Gleichner I");
INSERT INTO items (isactive, name) VALUES (1, "Dr. Raven Altenwerth PhD");
INSERT INTO items (isactive, name) VALUES (0, "Miss Dashawn Heller PhD");
INSERT INTO items (isactive, name) VALUES (1, "Miss Garry Klocko");
INSERT INTO items (isactive, name) VALUES (1, "Stacey Muller");
INSERT INTO items (isactive, name) VALUES (0, "Dr. Joana Morissette");
INSERT INTO items (isactive, name) VALUES (1, "Kayley Anderson DVM");
INSERT INTO items (isactive, name) VALUES (1, "Dr. Karson Bayer DVM");
INSERT INTO items (isactive, name) VALUES (0, "Bernadette Connelly");
INSERT INTO items (isactive, name) VALUES (1, "Mr. Daphnee Cronin");
INSERT INTO items (isactive, name) VALUES (1, "Mrs. Reginald Schinner");
INSERT INTO items (isactive, name) VALUES (0, "Jordyn Gottlieb");
INSERT INTO items (isactive, name) VALUES (1, "Mr. Gaylord Williamson");
INSERT INTO items (isactive, name) VALUES (1, "Luciano Hand");
INSERT INTO items (isactive, name) VALUES (0, "Estevan Reichel");
INSERT INTO items (isactive, name) VALUES (1, "Jena Will");
INSERT INTO items (isactive, name) VALUES (1, "Jevon Tremblay");
INSERT INTO items (isactive, name) VALUES (0, "Jacynthe Hills IV");
INSERT INTO items (isactive, name) VALUES (1, "Dr. Johnathon Pacocha III");
INSERT INTO items (isactive, name) VALUES (1, "Ms. Pierce Collier II");
INSERT INTO items (isactive, name) VALUES (0, "Malcolm Hegmann");
INSERT INTO items (isactive, name) VALUES (1, "Miss Esther Orn");
INSERT INTO items (isactive, name) VALUES (1, "Dr. Craig Block");
INSERT INTO items (isactive, name) VALUES (0, "Elta Schuster");
INSERT INTO items (isactive, name) VALUES (1, "Peyton Buckridge");
INSERT INTO items (isactive, name) VALUES (1, "Quinn Kulas");
INSERT INTO items (isactive, name) VALUES (0, "Chesley Stanton");
INSERT INTO items (isactive, name) VALUES (1, "Dr. Reyes Jaskolski PhD");
INSERT INTO items (isactive, name) VALUES (1, "Nelda Kovacek");
INSERT INTO items (isactive, name) VALUES (0, "Miss Dana Hettinger MD");
INSERT INTO items (isactive, name) VALUES (1, "Raoul Konopelski II");
INSERT INTO items (isactive, name) VALUES (1, "Hoyt Roob");
INSERT INTO items (isactive, name) VALUES (0, "Rosella Lockman");
INSERT INTO items (isactive, name) VALUES (1, "Eula Langosh");
INSERT INTO items (isactive, name) VALUES (1, "Catharine Leuschke");
INSERT INTO items (isactive, name) VALUES (0, "Roy Morissette");
INSERT INTO items (isactive, name) VALUES (1, "Ms. Garth Bernier MD");
